services:
  bgpalerter:
    image: nttgin/bgpalerter:latest
    volumes:
      - ./volume/config.yml:/opt/bgpalerter/config.yml
      - ./volume/prefixes.yml:/opt/bgpalerter/prefixes.yml
      - ./volume/logs:/opt/bgpalerter/logs

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

volumes:
  loki-data:
